name = "Bedrock Reloaded"
author = "SeriousFreezing"
version = "19.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dac96a910f230138649ae5e0cddc3293c01875afeef5c0a9c3984aec7c4dbb5f"

[versions]
fabric = "0.16.7"
minecraft = "1.21.1"
