name = "BedrockReloaded"
author = "SeriousFreezing"
version = "22.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6598b2bf50e2133af5150260b9274a791f1b17222481765c0051b62a7157d8ed"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
