name = "BedrockReloaded"
author = "SeriousFreezing"
version = "22.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1b3f4e24615c7e95bffe5e3d23b52d01ada15596360d95330598e07d0ff819e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
